### ISSUE TITLE
Order placing after market hours with AMO order is not working

### ISSUE THREAD

**Issue by chandre-gowda** [Shoonya-Dev/ShoonyaApi-py#1]
In File <python_path>\Lib\site-packages\NorenRestApiPy\NorenApi.py inside function "place_order"
"amo" orders were not considered even if we pass during order placement.

Inside function place_order add below line and it will place AMO order (in 'values' list)
 `values["amo"]       = amo`

**Comment by Shoonya-Dev** [comment]
issue is fixed

**Comment by bablukoli** [comment]
ERROR - CRUDEOIL Failed to place order for. Response: None
