### ISSUE TITLE
Start time for get_time_price_series off by 23 mins

### ISSUE THREAD

**Issue by gaurav-260** [Shoonya-Dev/ShoonyaApi-py#10]
Please see below screenshot. If one starts to pull the data for a specific minute, the time is coming out to be delayed by 23 mins. I have ensured that the timezone on my machine is Kolkata, hence passing the tzinfo argument. Could you please check why this delay.
![image](https://user-images.githubusercontent.com/71606439/148646845-11b71dd9-8f4a-4ae1-a7c4-8efa259664ad.png)

**Comment by gmnabeel** [comment]
Hi gaurav, what to enter in vendor code for finv?

**Comment by gaurav-260** [comment]
I am using my <userid_U>

**Comment by gmnabeel** [comment]
vc = "FA00000" for vendor code, similar to this?

& imei should be manually entered right?

I still get error when i type in my user ID in vendor code field

**Comment by TUNA2020** [comment]
What to put in the vendor code? userid is not working as vendor code.

**Comment by gaurav-260** [comment]
Did you even fix this? I don't see any resolution. Is it still offset by 23 mins? Why are you closing issues without proper explanation

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Concern has been forwarded to Tech Team. Will update shortly

**Comment by Shoonya-Dev** [comment]
please provide the values of strt and end, as we suspect timezone could be the issue

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

As we checked, its working fine. Please check your timezone or refer to the attached input and output of the code:

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/4e558735-c0fb-4b71-9e45-bd16859b18d6)
