### ISSUE TITLE
Place basket order APi not working

### ISSUE THREAD

**Issue by chintu1215** [Shoonya-Dev/ShoonyaApi-py#100]
Place basket is not working it gives error:
place_order() missing 6 required positional arguments: 'product_type', 'exchange', 'tradingsymbol', 'quantity', 'discloseqty', and 'price_type'

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your concern.

API is working Fine , Is the order you are placing through the API okay?
