### ISSUE TITLE
Error in Shoonya API when invoked.

### ISSUE THREAD

**Issue by asnewton** [Shoonya-Dev/ShoonyaApi-py#102]
TypeError                                 Traceback (most recent call last)
<ipython-input-10-cf59431bebf9> in <module>
      1 logging.basicConfig(level=logging.DEBUG)
      2 
----> 3 api = ShoonyaApiPy()

~\Desktop\Python DS\ShoonyaApi-py-master\ShoonyaApi-py-master\api_helper.py in __init__(self)
     40 class ShoonyaApiPy(NorenApi):
     41     def __init__(self):
---> 42         NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')
     43         global api
     44         api = self

TypeError: __init__() missing 1 required positional argument: 'eodhost'

**Comment by phpgraduate** [comment]
Add eodhost to api_helper.py
In my case:
NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/', eodhost='https://shoonya.finvasia.com/chartApi/getdata/')

**Comment by guten5912** [comment]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\python t\shoonya_login.py", line 56, in <module>
    Shoonya_login()
  File "C:\Users\HP\Desktop\python t\shoonya_login.py", line 52, in Shoonya_login
    print(ret['susertoken'])
TypeError: 'NoneType' object is not subscriptable

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please clone the below-attached link and run your code; its working fine.

https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/api_helper.py
