### ISSUE TITLE
Bracket Order through python API is not working 

### ISSUE THREAD

**Issue by propbala03** [Shoonya-Dev/ShoonyaApi-py#105]
After the Buy/Sell order executed, the SL and target orders are place at higher values mostly the upper and lower circuit. Team may pl check get back

**Comment by vipinagrahari** [comment]
The order sl price and book profit price should be number of points and not the actual value.

e.g. if 150 is entry price and you want 155 to be profit and 145 to be SL then 
**book profit = 5, and SL price = 5**

**Comment by abhisheksoni27** [comment]
what about trailing price?
