### ISSUE TITLE
Invalid Input :  Invalid Vendor code

### ISSUE THREAD

**Issue by MereHanumanji** [Shoonya-Dev/ShoonyaApi-py#106]
I am getting "Invalid Input :  Invalid Vendor code" error on login.

I have tried even copy paste from prism security page it self. I am unable to understand what an go wrong with VC.

Kindly help me.

**Comment by suresh-n** [comment]
recreating Api key helped me

**Comment by MereHanumanji** [comment]
Thanks a ton for a quick response
Regenerating the API key resolved the issue.
