### ISSUE TITLE
16052 function not available

### ISSUE THREAD

**Issue by Kirankio** [Shoonya-Dev/ShoonyaApi-py#107]
Orders getting rejected "16052 function not available" for SL-LMT orders with trigger price and price mentioned , kindly help on this issue

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your Concern.

This is basically Exchange Error, For which, you can refer to the link (https://www1.nseindia.com/technology/content/nnf/TP_FO_Trimmed_NNF_PROTOCOL_9.21.pdf )
Finally, you need to check at your end Is the order you are placing through the API okay?
