### ISSUE TITLE
No response while getting historical data

### ISSUE THREAD

**Issue by pushpen** [Shoonya-Dev/ShoonyaApi-py#109]
api.get_daily_price_series seems to be stuck.
Not getting any response
Please check.

**Comment by ghostjat** [comment]
same issue here returning empty array.

**Comment by trivalent** [comment]
Experiencing the same. The same request works with Curl and data is returned, but the API returns HTTP 502. 
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//EODChartData HTTP/1.1" 502 None
DEBUG:NorenRestApiPy.NorenApi:<Response [502]>

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

As we checked, its working fine. Please check your input parameters, or please check the attached input and output of the code:

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/f4ef0f26-2c31-4abc-b1a9-6f4d4ba7dc67)
