### ISSUE TITLE
How to pull data for Day candles?

### ISSUE THREAD

**Issue by bailakare** [Shoonya-Dev/ShoonyaApi-py#11]
Hi,

I would like to know how to pull data day-wise 1D, week-wise 1W and month-wise 1M?

In the documentation, I see Candle size in minutes (1,3,5,10,15,30,60,120,240). However nothing has been specified for D/W/M.

**Comment by ajay-webdev** [comment]
you can use 
url:

https://shoonya.finvasia.com/chartApi/getdata/

payload:

jData={"uid":"*userid*","exch":"*exchange*","token":"*trading-symbol*","st":"*start-timestamp*","et":"*end-timestap*"}&jKey=*api-key*

change *abc* with your parameters

**Comment by Shoonya-Dev** [comment]
Please refer to example_market.py option ('d => get daily data')
https://github.com/Shoonya-Dev/ShoonyaApi-py/#md-get_daily_price_series
