### ISSUE TITLE
run_forever() : unexpected keyword argument ping_payload

### ISSUE THREAD

**Issue by rrgiyer** [Shoonya-Dev/ShoonyaApi-py#112]
getting the below error while trying to open WS. 

WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your Concern.

Update the WebSocket client, by updating the python package **pip update websocket_client**
