### ISSUE TITLE
Can't run the websocket on my Mac but it's working fine on Windows. Please tell what to do?

### ISSUE THREAD

**Issue by Nifty69Trader** [Shoonya-Dev/ShoonyaApi-py#114]
DEBUG:NorenRestApiPy.NorenApi:<websocket._app.WebSocketApp object at 0x12a6f3c10>
ERROR:websocket:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997) - goodbye
DEBUG:NorenRestApiPy.NorenApi:None

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

If you're encountering an SSL certificate verification issue, consider the following steps:
1️⃣ Ensure your system's date and time are accurate.
2️⃣ Check if the SSL certificate is expired.
3️⃣ Try updating your Python libraries, especially the one causing the error.
