### ISSUE TITLE
Different Date Time Format for same request for two different day 

### ISSUE THREAD

**Issue by milansoliya4210** [Shoonya-Dev/ShoonyaApi-py#118]
@kambalatech @Shoonya-Dev @Nikhesh 
![finvesia_error](https://user-images.githubusercontent.com/40118048/231794319-b7b9f6ea-6789-4b90-818e-0f29cf239311.png)

I have request python API `ret.get_time_price_series(exchange=’NSE’, token=’ 26000’, starttime=’ 1681223108.44189’ , endtime=’1681395908.44189’ interval=’120’) `
and response received as 
`[{'stat': 'Ok', 'time': '13-04-2023 15:15:00', 'ssboe': '1681379100', 'into': '17836.60', 'inth': '17841.50', 'intl': '17826.40', 'intc': '17828.00', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '13-04-2023 13:15:00', 'ssboe': '1681371900', 'into': '17749.90', 'inth': '17837.40', 'intl': '17744.90', 'intc': '17836.55', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '13-04-2023 11:15:00', 'ssboe': '1681364700', 'into': '17746.90', 'inth': '17777.60', 'intl': '17729.70', 'intc': '17750.00', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '13-04-2023 09:15:00', 'ssboe': '1681357500', 'into': '17788.70', 'inth': '17827.25', 'intl': '17740.80', 'intc': '17747.60', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '12-04-2023 15:15:00', 'ssboe': '1681292700', 'into': '17812.35', 'inth': '17915.50', 'intl': '17805.25', 'intc': '17807.30', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '12-04-2023 13:15:00', 'ssboe': '1681285500', 'into': '17792.25', 'inth': '17819.05', 'intl': '17767.25', 'intc': '17812.25', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '12-04-2023 11:15:00', 'ssboe': '1681278300', 'into': '17753.90', 'inth': '17795.30', 'intl': '17750.70', 'intc': '17792.35', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}, {'stat': 'Ok', 'time': '12-04-2023 09:15:00', 'ssboe': '1681271100', 'into': '17756.20', 'inth': '17779.40', 'intl': '17717.80', 'intc': '17754.35', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi': '0'}]`

**### I found that the time format is different in both day 12th April and 13th April and due to that code breaks, please request to team to fix date time format and also mentioned in API document .**

**Comment by Nikhesh** [comment]
Hi sir,

As shown in your mail the response shows datetime in the correct format.
The screenshot seems to be after a transformation of data. Kindly check the
code at your end.

[{'stat': 'Ok', 'time': '13-04-2023 15:15:00', 'ssboe': '1681379100',
'into': '17836.60', 'inth': '17841.50', 'intl': '17826.40', 'intc':
'17828.00', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '13-04-2023 13:15:00', 'ssboe': '1681371900',
'into': '17749.90', 'inth': '17837.40', 'intl': '17744.90', 'intc':
'17836.55', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '13-04-2023 11:15:00', 'ssboe': '1681364700',
'into': '17746.90', 'inth': '17777.60', 'intl': '17729.70', 'intc':
'17750.00', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '13-04-2023 09:15:00', 'ssboe': '1681357500',
'into': '17788.70', 'inth': '17827.25', 'intl': '17740.80', 'intc':
'17747.60', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '12-04-2023 15:15:00', 'ssboe': '1681292700',
'into': '17812.35', 'inth': '17915.50', 'intl': '17805.25', 'intc':
'17807.30', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '12-04-2023 13:15:00', 'ssboe': '1681285500',
'into': '17792.25', 'inth': '17819.05', 'intl': '17767.25', 'intc':
'17812.25', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '12-04-2023 11:15:00', 'ssboe': '1681278300',
'into': '17753.90', 'inth': '17795.30', 'intl': '17750.70', 'intc':
'17792.35', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}, {'stat': 'Ok', 'time': '12-04-2023 09:15:00', 'ssboe': '1681271100',
'into': '17756.20', 'inth': '17779.40', 'intl': '17717.80', 'intc':
'17754.35', 'intvwap': '0.00', 'intv': '0', 'intoi': '0', 'v': '0', 'oi':
'0'}]


*Thanks & Regards,*
*Nikhesh P*

Mob : +91-9880093697 | Web : www.kambala.co.in | E-mail:
***@***.***
