### ISSUE TITLE
getting FINNIFTY dname wrong 

### ISSUE THREAD

**Issue by suresh-n** [Shoonya-Dev/ShoonyaApi-py#119]
dname suppose to be have date its missing on FINNIFTY data , nifty and banknifty its good.

{'stat': 'Ok', 'values': [{'exch': 'NFO', 'token': '55913', 'tsym': 'FINNIFTY02MAY23P19000', 'weekly': 'W1', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '55912', 'tsym': 'FINNIFTY02MAY23C19000', 'weekly': 'W1', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '37151', 'tsym': 'FINNIFTY09MAY23P19000', 'weekly': 'W2', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '37150', 'tsym': 'FINNIFTY09MAY23C19000', 'weekly': 'W2', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '43671', 'tsym': 'FINNIFTY16MAY23P19000', 'weekly': 'W3', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '43670', 'tsym': 'FINNIFTY16MAY23C19000', 'weekly': 'W3', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '47581', 'tsym': 'FINNIFTY23MAY23P19000', 'weekly': 'W4', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '47580', 'tsym': 'FINNIFTY23MAY23C19000', 'weekly': 'W4', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '42766', 'tsym': 'FINNIFTY30MAY23P19000', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '42764', 'tsym': 'FINNIFTY30MAY23C19000', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '59182', 'tsym': 'FINNIFTY27JUN23P19000', 'dname': 'FINNIFTY JUN 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '59181', 'tsym': 'FINNIFTY27JUN23C19000', 'dname': 'FINNIFTY JUN 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '51927', 'tsym': 'FINNIFTY25JUL23P19000', 'dname': 'FINNIFTY JUL 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '51909', 'tsym': 'FINNIFTY25JUL23C19000', 'dname': 'FINNIFTY JUL 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}]}

**Comment by suresh-n** [comment]
{'stat': 'Ok', 'values': [{'exch': 'NFO', 'token': '55913', 'tsym': 'FINNIFTY02MAY23P19000', 'weekly': 'W1', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '55912', 'tsym': 'FINNIFTY02MAY23C19000', 'weekly': 'W1', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '37151', 'tsym': 'FINNIFTY09MAY23P19000', 'weekly': 'W2', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '37150', 'tsym': 'FINNIFTY09MAY23C19000', 'weekly': 'W2', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '43671', 'tsym': 'FINNIFTY16MAY23P19000', 'weekly': 'W3', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '43670', 'tsym': 'FINNIFTY16MAY23C19000', 'weekly': 'W3', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '47581', 'tsym': 'FINNIFTY23MAY23P19000', 'weekly': 'W4', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '47580', 'tsym': 'FINNIFTY23MAY23C19000', 'weekly': 'W4', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '42766', 'tsym': 'FINNIFTY30MAY23P19000', 'dname': 'FINNIFTY MAY 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '42764', 'tsym': 'FINNIFTY30MAY23C19000', 'dname': 'FINNIFTY MAY 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '59182', 'tsym': 'FINNIFTY27JUN23P19000', 'dname': 'FINNIFTY JUN 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '59181', 'tsym': 'FINNIFTY27JUN23C19000', 'dname': 'FINNIFTY JUN 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '51927', 'tsym': 'FINNIFTY25JUL23P19000', 'dname': 'FINNIFTY JUL 19000 PE ', 'optt': 'PE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}, {'exch': 'NFO', 'token': '51909', 'tsym': 'FINNIFTY25JUL23C19000', 'dname': 'FINNIFTY JUL 19000 CE ', 'optt': 'CE', 'instname': 'OPTIDX', 'pp': '2', 'ls': '40', 'ti': '0.05'}]}

**Comment by Shoonya-Dev** [comment]
Hi, We request please reach us with the query at apisupport@shoonya.com so that we can confirm & check the exact issue.
