### ISSUE TITLE
api.start_websocket with interval time like 1min, 3min, 5min 

### ISSUE THREAD

**Issue by gudipudipradeep** [Shoonya-Dev/ShoonyaApi-py#12]
@Shoonya-Dev  Please can you guide me stream web socket with interval option to like 1min, 3min, 5min, 15min ... so on
@kambalatech

**Comment by gudipudipradeep** [comment]
Just put like this below
vc      : 'FAXXXX_U'
FAXXXX  Replace with clientid

**Comment by Shoonya-Dev** [comment]
This is real time feed only not for vwap or conflated data
