### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by utkbagal** [Shoonya-Dev/ShoonyaApi-py#123]
Hi, I'm getting this error while logging in through Shoonya API. Can you help?

requests.exceptions.SSLError: HTTPSConnectionPool(host='api.shoonya.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

**Comment by setushah1** [comment]
Error :

HTTPSConnectionPool(host='api.shoonya.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

**Comment by bharath0292** [comment]
On my websocket error callback
Error: 
__on_error_callback - 197 - INFO - error_callback [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1002)

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

If you're encountering an SSL certificate verification issue, consider the following steps:
1️⃣ Ensure your system's date and time are accurate.
2️⃣ Check if the SSL certificate is expired.
3️⃣ Try updating your Python libraries, especially the one causing the error.

**Comment by ghost** [comment]
@Shoonya-Dev  please help facing similar issue...

@setushah1 @bharath0292 @utkbagal  - can u pls share the steps to fix the issue.
