### ISSUE TITLE
ERROR:websocket:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002) - goodbye

### ISSUE THREAD

**Issue by amitsingh24into7** [Shoonya-Dev/ShoonyaApi-py#124]
I am getting Above subject error while calling API (https://api.shoonya.com:443 "POST /NorenWClientTP//SearchScrip)

Please help, an settings needs to be done in the system. i installed pycertifi and uploaded pem certifcate in my machine as well

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your Concern.

If you are using Windows and you have already imported the CA in the trusted DB store, you can install the package python-certifi-win32 that automagically will use the same certificates from the Trusted DB store.

pip install python-certifi-win32

**Comment by ghost** [comment]
dear @Shoonya-Dev ,

added the certificate 'venv\Lib\site-packages\certifi\cacert.pem' in trusted Root and installed the pip mention above, still getting error.

@amitsingh24into7 , could you please help how the issue resolved.

**Comment by ghost** [comment]
@Shoonya-Dev  how to import the CA in the trusted DB store and which certificate, please help....

@amitsingh24into7 , if you issue has resolved, can u pls help.
