### ISSUE TITLE
get_daily_price_series() NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by DuizzieDoCode** [Shoonya-Dev/ShoonyaApi-py#125]
sometime it give response to this **res = requests.post(url, data=payload, headers=headers)** sometimes it stuck resulting **len(res.text) == 0:**
URL = https://api.shoonya.com/NorenWClientTP//EODChartData

**Comment by tarakantnayak** [comment]
same issue. Some times it works and some times it gets stuck.
it returns status code as 200, but the result is empty.

startdate  = datetime.today() - timedelta(days=8)
enddate  = datetime.today()
res = shoonya_api.get_daily_price_series(exchange="NFO", tradingsymbol="NIFTY27JUL23F", startdate=startdate.timestamp(), enddate=enddate.timestamp())

**Comment by onlydevelop** [comment]
Yes, I am not getting any data from that.

**Comment by damodaran** [comment]
I am trying to fetch 5 min data, I got it working till 9.30 and then after it return data till 9.30 not no data for 9.35 onwards.

**Comment by amresh1985** [comment]
same issue. Some times it works and some times it gets stuck.
it returns status code as 200, but the result is empty. 
working for some symbol but not for few symbol.

For example working for GOLDBEES-EQ but not for TNIDETF-EQ

startdate = datetime.today() - timedelta(days=50)
enddate = datetime.today() - timedelta(days=1)

exch  = 'NSE'
tsym = 'GOLDBEES-EQ'
ret = api.get_daily_price_series(exchange=exch, tradingsymbol=tsym , startdate=startdate.timestamp(), enddate=enddate.timestamp())
print(ret)

**Comment by rpaddu** [comment]
It is not working. len(ret) is 0. any solution?

**Comment by akum42** [comment]
Any update on this, previously it was working fine

**Comment by rpaddu** [comment]
Hi,

When I sent you the first mail, it was not working.
After I got your reply it was working though I did not change anything in the code.
Now it is working too..

Thanks
RP
________________________________

**Comment by rpaddu** [comment]
Hi,

Last evening around 730pm it did not work again. But it works this morning.

Is there scheduled downtime when get_daily_price_series will not work? It is very inconsistent.


Regards,

Padmanabhan . R

________________________________

**Comment by Govardhanab3339** [comment]
I am not getting responses from get_daily_price_series for NSE and indices "NIFTY INDEX and NIFTY BANK" , are you getting ? , how to get

> 
> As we checked, its working fine Please refer to the attached input and output of the code:
> 
> ![image](https://private-user-images.githubusercontent.com/94599203/334311644-bae1af42-28b7-482e-b750-b9a21c307c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODY2MzgsIm5iZiI6MTcxNjg4NjMzOCwicGF0aCI6Ii85NDU5OTIwMy8zMzQzMTE2NDQtYmFlMWFmNDItMjhiNy00ODJlLWI3NTAtYjlhMjFjMzA3YzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA4NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNGM3NzI1N2ZmODE4YmYyYWVlZGNkMTAzZmQ3MTMwNTY2ZmJkZWI2MTdkMTg2OTY3NTNiOTI0NDQzZGZlOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z17PgYscyUDO01VX5MGiByAVIfP_E9J7EkaP_BGNCb8)

**Comment by pankaj3009** [comment]
doesn't work
end = dt.datetime.today()
end = end.replace(hour=9,minute=15,second=0,microsecond=0)
start = end - dt.timedelta(days=30)
sh.api.get_daily_price_series(exchange="NSE",tradingsymbol="INFY-EQ",startdate=start.timestamp(),enddate=end.timestamp())
---
[]

**Comment by suresh-n** [comment]
yeah this work sometime and sometime it did not also its very slow. since long time its not working.

**Comment by pankaj3009** [comment]
its slow. and works intermittently. best way, in case you are intent on using shoonya for market data, is to use a signal to timeout and reattempt like so

                attempts = 3
                wait_seconds = 2
                data = None
                
                for attempt in range(attempts):
                    start_time = time.time()
                    signal.alarm(2)  # Trigger a timeout in 2 seconds
                    try:
                        data = self.api.get_daily_price_series(
                            exchange=exch,
                            tradingsymbol=trading_symbol,
                            startdate=date_start.timestamp(),
                            enddate=date_end.timestamp(),
                        )
                        # If call succeeds, break out of loop
                        break
                    except Exception as e:
                        data = None
                
                    finally:
                        signal.alarm(0)  # Cancel the alarm
                
                    elapsed = time.time() - start_time
                    if elapsed < wait_seconds:
                        logger.info(f"Reattempting to get daily data for {row_outer['long_symbol']}")
                        time.sleep(wait_seconds - elapsed)

also remember that it will not return today's bar, so you will need to build it using get_time_price_series. So need 2 api calls atleast.

**Comment by vnkjoshi** [comment]
get_daily_price_series working perfectly with BSE but not NSE. What the issue, can someone help me please.
