### ISSUE TITLE
Midcap select index is not available in searchscrip and master contract files

### ISSUE THREAD

**Issue by rajindersingh041** [Shoonya-Dev/ShoonyaApi-py#126]
Midcap select index is not available throught searchscrip method

when running shoonya.searchscrip("NSE","NIFTY")
it returns

{'stat': 'Ok', 'values': [{'exch': 'NSE', 'token': '10690', 'tsym': 'NIFTYQLITY-EQ', 'cname': 'BIRLASLAMC - NIFTYQLITY', 'instname': 'EQ', 'pp': '2', 'ls': 
'1', 'ti': '0.01'}, {'exch': 'NSE', 'token': '10576', 'tsym': 'NIFTYBEES-EQ', 'cname': 'NIP IND ETF NIFTY BEES', 'instname': 'EQ', 'pp': '2', 'ls': '1', 'ti': '0.01'}, {'exch': 'NSE', 'token': '26037', 'tsym': 'Nifty Fin Service', 'nontrd': '1', 'cname': 'FIN NIFTY', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 
'ti': '0.05'}, {'exch': 'NSE', 'token': '26009', 'tsym': 'Nifty Bank', 'nontrd': '1', 'cname': 'NIFTY BANK', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 'ti': '0.05'}, {'exch': 'NSE', 'token': '26000', 'tsym': 'Nifty 50', 'nontrd': '1', 'cname': 'NIFTY INDEX', 'instname': 'UNDIND', 'pp': '2', 'ls': '1', 'ti': '0.05'}]}

and in master contract files also midcap index is not present in NSE file.

Could you please update the master contract and api?

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your concern.

We have updated the NIFTY MIDCAP SELECT Index in [Symbol Master File](https://api.shoonya.com/NSE_symbols.txt.zip)
Kindly Check.
