### ISSUE TITLE
Login Issue using Shoonya API

### ISSUE THREAD

**Issue by nihadshibilec** [Shoonya-Dev/ShoonyaApi-py#127]
I am getting this error while login:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.shoonya.com:443
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//QuickAuth HTTP/1.1" 200 105
DEBUG:NorenRestApiPy.NorenApi:Reply:{"request_time":"15:12:06 23-07-2023","stat":"Not_Ok","emsg":"Invalid Input : User Not enabled on : API"}

**Comment by suresh-n** [comment]
Please work shoonya support as it showing user not enabled. Fastest way is login into https://prism.finvasia.com/ and chat  they will enable instantly.

**Comment by Shoonya-Dev** [comment]
@nihadshibilec 
Greetings from Shoonya!

Thanks for your concern.

API is not enabled at your client code, Kindly share your client code on apisupport@shoonya.com, Team will enable the API access for your client code.

Team Shoonya
