### ISSUE TITLE
invalid vendor code err

### ISSUE THREAD

**Issue by ajay-webdev** [Shoonya-Dev/ShoonyaApi-py#13]
DEBUG:NorenRestApiPy.NorenApi:Reply:{"stat":"Not_Ok","emsg":"Invalid Input :  Invalid Vendor code"}

i entered vendor code as mentioned below : 
vc='FA******_U'

**Comment by suresh-n** [comment]
I'm seeing same error

**Comment by AMXIT** [comment]
> DEBUG:NorenRestApiPy.NorenApi:Reply:{"stat":"Not_Ok","emsg":"Invalid Input : Invalid Vendor code"}
> 
> i entered vendor code as mentioned below : vc='FA******_U'

what we have to enter in vender code??

**Comment by ajay-webdev** [comment]
got this error today

DEBUG:NorenRestApiPy.NorenApi:Reply:{"request_time":"11:27:28 20-01-2022","stat":"Not_Ok","emsg":"Invalid Input : User Not enabled on : API"}

**Comment by ajay-webdev** [comment]
> > DEBUG:NorenRestApiPy.NorenApi:Reply:{"stat":"Not_Ok","emsg":"Invalid Input : Invalid Vendor code"}
> > i entered vendor code as mentioned below : vc='FA******_U'
> 
> what we have to enter in vender code??

add your userid for vc with "_U" at the end
