### ISSUE TITLE
get Current day's trading costs  

### ISSUE THREAD

**Issue by Iss-in** [Shoonya-Dev/ShoonyaApi-py#132]
Is there a way to get total trading charges for all your intraday trades using python api , Just like we can get the pnl. 

Not able to find any info in api documentations, please help me figure it out if possible

**Comment by Shoonya-Dev** [comment]
You Can Check the total trading charges from via login reports.shoonya.com , If More Information We request Kindly Contact Our Client or Chat Support Team for Such Query, they will assist You better on it.
You can call below mention dedicated client support team for further assistance.
- 📞 Support: +91-172 4740000, 6750000 & Email at clientsupport@shoonya.com
