### ISSUE TITLE
Can not connect to Websocket

### ISSUE THREAD

**Issue by DeepBhuptani** [Shoonya-Dev/ShoonyaApi-py#133]
Hello,
I am getting this error while trying to connect to websocket. Please help me how to resolve this. Thanks.

```
websocket run forever ended in exception, socket is already opened
websocket run forever ended in exception, socket is already opened
websocket run forever ended in exception, socket is already opened
websocket run forever ended in exception, socket is already opened
websocket run forever ended in exception, socket is already opened
```

**Comment by suresh-n** [comment]
look like your program trying to run api.startwebsocket() second time so its showing this error.

**Comment by Shoonya-Dev** [comment]
@DeepBhuptani :- You have Tried to open the socket twice. Kill one & then try.

**Comment by tradeunifox** [comment]
is this code correct for websocket? its working only ret show none. and i remove the id, password for security reasons. 



import os
import logging
import pyotp
from NorenRestApiPy.NorenApi import NorenApi

class ShoonyaApiPy(NorenApi):
    def __init__(self):
        super().__init__(host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')
        global api
        api = self

logging.basicConfig(level=logging.DEBUG)

api = ShoonyaApiPy()

token = ''
otp = pyotp.TOTP(token).now()
user = os.getenv('SHOONYA_USER' '')
pwd = os.getenv('SHOONYA_PASS', '')
factor2 = otp
vc = os.getenv('VENDOR_CODE', '')
app_key = os.getenv('APP_KEY', '')
imei = os.getenv('IMEI', '')

ret = api.login(userid=user, password=pwd, twoFA=otp, vendor_code=vc, api_secret=app_key, imei=imei)


feed_opened = False

def event_handler_feed_update(tick_data):
 print(f"feed update {tick_data}")

def event_handler_order_update(order):
 print(f"feed update {order}")

def open_callback():
 global feed_opened
 feed_opened = True

api.start_websocket( order_update_callback=event_handler_order_update,
 subscribe_callback=event_handler_feed_update,
socket_open_callback=open_callback)

while(feed_opened==False):
 pass

ret = api.subscribe('NSE|22')
print(ret)
