### ISSUE TITLE
Live Feed data not coming

### ISSUE THREAD

**Issue by gousKDT** [Shoonya-Dev/ShoonyaApi-py#134]
In my code,

I have added this piece of code, inpsite of that I don't see any live data coming. The callback function is not getting called to give me the live data.

ret = api.start_websocket(order_update_callback=event_handler_order_update,
                                subscribe_callback=event_handler_option_update, 
                                socket_open_callback=open_callback_option_open)

    print("Will Open WebSocket now", ret)                            
    while (socket_opened == False):  # wait till socket open & then subscribe
        pass
    # subscribe to a single token
    ConToken = "NFO" + "|" + token_value
    #ret = api.subscribe(ConToken, feed_type="t")
    #api.subscribe(f'NFO|{token_value}', "t")
    ret = api.subscribe('NFO|85999', feed_type="t")
    print("SUBSCRIBED...", ConToken)

**Comment by gousKDT** [comment]
Below function should get called, but I don't see this is being called. So unable to understand the issue here. Appreciate if any help.

def event_handler_option_update(message):
   print(message)

**Comment by gousKDT** [comment]
So far no support. 

@Shoonya-Dev Any idea?

**Comment by pashriva** [comment]
+1
The open_callback() is never called

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/5595200/407070d2-5458-4c15-bd0e-65c7cc626f91)

**Comment by Shoonya-Dev** [comment]
We've taken the necessary steps to address the problem, and we believe it has been resolved satisfactorily. However, should you encounter any further difficulties or if the issue resurfaces, please don't hesitate to reach out to us.

Additionally, for any ongoing or future support needs, feel free to contact us via our dedicated support email at apisupport@shoonya.com. We're here to assist you promptly and ensure a seamless experience.
