### ISSUE TITLE
not  get quatos data 

### ISSUE THREAD

**Issue by Shubhamtradehull** [Shoonya-Dev/ShoonyaApi-py#135]
script_to_scan = 'NIFTY INDEX' #future_script_to_scan(watchlist)
    token = find_token(script_to_scan)
    exch  = 'NSE'
    script_quate = api.get_quotes(exch,token)
    
    
    i am getting error not getting data 
    error as " *** TypeError: Object of type int64 is not JSON serializable"

**Comment by suresh-n** [comment]
is your token return properly  from find_token function? I will do something like this.

script_to_scan = 'NIFTY INDEX'
res_pe = api.searchscrip("NSE", searchtext=script_to_scan)
token = res_pe['values'][0]['token']
exch = 'NSE'
script_quate = api.get_quotes(exch,token)
script_quate

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

As we checked, it was working fine. Please check your input parameters or refer to the below-attached input and output of the code:

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/466f46fb-92c7-4b6b-8386-8a4aba54ab22)
