### ISSUE TITLE
Api is not defined in documentation 

### ISSUE THREAD

**Issue by kalilinux-png** [Shoonya-Dev/ShoonyaApi-py#136]
api is not defined, more details are required on how to import API, this will confuse new users who will be using API

this is code in documentation where API is not defined 
https://github.com/Shoonya-Dev/ShoonyaApi-py#md-login

**Comment by suresh-n** [comment]
you can make use of test_api.py file in repo, https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/test_api.py

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please use the below-attached URL for the login via API:

https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/test_api.py
