### ISSUE TITLE
Documentation Need To Be updated 

### ISSUE THREAD

**Issue by kalilinux-png** [Shoonya-Dev/ShoonyaApi-py#137]
The Documentation Does not have any information on login through Totp, it is quite easy but still, it should be in documentation.
@Shoonya-Dev , @kambalatech , @Nikhesh do you accept PR on this REPO? . if yes have a look at pending PR so that new PR can be created 👍

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

We will forward this to the concerned team, and we will update on the documentation shortly.
