### ISSUE TITLE
get_time_price_series not fetching latest data

### ISSUE THREAD

**Issue by damodaran** [Shoonya-Dev/ShoonyaApi-py#138]
I am trying to fetch 5 min data, I got it working till 9.40 and then after it return data till 9.40 only not no data for 9.40 onwards. As you can see in the screenshot, system time is 9.51 but last row shows data of 9.40
![get price series](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/1776773/24bf9b38-068b-47a4-92e9-f9617c6e2dd5)

Is there any length limitation applicable for this API? I am trying to fetch last 60 days data with 5 minute candle

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

As we checked its working fine please check below attached input and output of the code:

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/8807ef64-9a1d-46dc-82d9-a329b704f348)
