### ISSUE TITLE
time_price_series for SENSEX

### ISSUE THREAD

**Issue by khanavijit** [Shoonya-Dev/ShoonyaApi-py#141]
Hi I can get individual time price series, for options like NIFTY, BANKNIFTY , FINNIFTY, but for Sensex it is not working , it gives an error 'Unknown', I have use exchange as BFO/BSE , and tied with weekly expiry symbol(both symbol and trading_symbol) none seems to be working , get quote is working.

**Comment by Shoonya-Dev** [comment]
As We have Checked at Our Level, for BSE & BFO. for both working fine. Please find the screenshot as an evidence. 

![image_2024_03_20T05_19_56_439Z](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/c7290ca8-dea6-418a-9769-7ae6ac90b1bf)
![image_2024_03_20T05_24_31_934Z](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/94599203/1f4b3627-8c0a-47f1-b5d3-3d19d08f8dbf)
