### ISSUE TITLE
get_time_price_series has time gaps in the data

### ISSUE THREAD

**Issue by trivalent** [Shoonya-Dev/ShoonyaApi-py#142]
Query:
enddate = datetime(day=1, month=1, year=2023)
startdate=datetime(day=28, month=12, year=2023)
print(f"{enddate} -> {startdate}")
ret = api.get_time_price_series("NSE", "RELIANCE-EQ", interval=60, starttime=enddate.timestamp(), endtime=startdate.timestamp())

Output:
The query is executed successfully and I get 1414 Rows of data 

Issue:
The response has missing data for several time, for ex
For date 28-04-2023, the response doesn't have price data for the interval 12:15:00. The previous interval 11:15:00 and 13:15:00 data is available. 
Similarly, the data is missing for several other intervals. Attached is the RAW response received from above query.
Attached here is the raw response from Finvasia and CSV from Yahoo Data query, which reports all the data correctly.

Attachments:
1. [finvasia_data_missing_issue.txt](https://github.com/Shoonya-Dev/ShoonyaApi-py/files/13798800/finvasia_data_missing_issue.txt)
2. [RELIANCE.NS_yahoo.csv](https://github.com/Shoonya-Dev/ShoonyaApi-py/files/13798803/RELIANCE.NS_yahoo.csv)

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

As we checked, there is no delay in data. Please refresh your token and try again.
