### ISSUE TITLE
modifiy order showing method not allowed

### ISSUE THREAD

**Issue by KesarwaniConsolidated** [Shoonya-Dev/ShoonyaApi-py#144]
while i use modify order and pass hardcoded value for modifing order it get modified but if i use it as variable value or in generalise format it show method not allowed

**Comment by KesarwaniConsolidated** [comment]
ltp=10
a="NIFTY11JAN24C21700"
b="24401001307465"
ret = api.modify_order(exchange='NFO', tradingsymbol=a, orderno=b,
                                        newquantity=50, newprice_type='SL-LMT', newprice=ltp+2, newtrigger_price=ltp+1)
response is     "method not allowed" but if i do this 

ltp=10
ret = api.modify_order(exchange='NFO', tradingsymbol="NIFTY11JAN24C21700", orderno="24401001307465",
                                        newquantity=50, newprice_type='SL-LMT', newprice=ltp+2, newtrigger_price=ltp+1)
it get triggered

**Comment by Shoonya-Dev** [comment]
We request please reach out to our API Support Team at **apisupport@shoonya.com**
