### ISSUE TITLE
What is API Rate Limit Per Day?

### ISSUE THREAD

**Issue by Ranjith5770** [Shoonya-Dev/ShoonyaApi-py#146]
As per Documentation Mentioned only 20 Req per Second and 200 req per Min. 

**Is Any Rate limit for Per Day and Per Hour?**

Is API Limit restriction Only orders or any other API..?

**Comment by Shoonya-Dev** [comment]
As we have given in the documentation only 20 Request per Second and 200 request per Minute, currently we do not recommend day wise and hour wise in the structure.
For More Query, please reach out us at apisupport@shoonya.com
