### ISSUE TITLE
Lag in order processing time

### ISSUE THREAD

**Issue by Noob-Coder18** [Shoonya-Dev/ShoonyaApi-py#148]
6/10 times the orders are processed lag free, but rest of time connection timeout error occurs which consumes 8-10 seconds easily and program is stuck until this error is received thus creating a delay of 8-10s in repeating the same order. Requested to resolve this error
1) why does connection time out error occurs so frequently ? 
2) atleast requesting to add a timeout option for the same so that user can edit the timeout as desired instead of waiting for 8-10 seconds

**Comment by Shoonya-Dev** [comment]
Greeting From Shoonya By Finvasia
Thanks for the Concern
Connection time out indicates that you are breaching the given time line, please follow the rate limit given in the order.
[](https://shoonya.com/api-documentation#ratelimit)

If you have another concern please reach out to us at apisupport@shoonya.com
