### ISSUE TITLE
Nifty Close price showing incorrect

### ISSUE THREAD

**Issue by gaurav-260** [Shoonya-Dev/ShoonyaApi-py#15]
![image](https://user-images.githubusercontent.com/71606439/152683786-3ca70096-b06b-4adc-8036-3ab33218aade.png)

Please see above image. Nifty has closed on 17516 on Friday (Feb-4-2022), however, the API is giving it as 16500.

Checked for individual stocks and it is working fine, not sure what is the issue with this. Please check and resolve.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Comment.

Hopefully Websocket was slow at that time , so that price was delay.
