### ISSUE TITLE
lag in getting time price series data 

### ISSUE THREAD

**Issue by Noob-Coder18** [Shoonya-Dev/ShoonyaApi-py#153]
api.get_time_price_series  - is fetching data but the data is delayed by atleast ten minutes. For example if i try to get data at 10.16 AM then still the candle data is present for only 10.05 candle. Both 10.10 and 10.15 AM candle data is misssing. So it is lagging by atleast 10 minutes.  Request to reduce this lag.

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

There is no delay in data. Please refresh your token and try again.
