### ISSUE TITLE
WEEKLY OPTION CHAIN DATA 

### ISSUE THREAD

**Issue by KesarwaniConsolidated** [Shoonya-Dev/ShoonyaApi-py#154]
IN THE  API OF 'GET OPTION CHAIN DATA ' HOW TO GET WEEKLY OPTION CHAIN THEIR IS NO WAY I FIND

**Comment by TWP80** [comment]
```
api.get_option_chain(exchange = 'NFO',
                     tradingsymbol = 'NIFTY25APR24F',
                     strikeprice = 22700,
                     count = 5)
```
provide tradingsymbol nifty future contract, you can find nifty future contract using 
`api.searchscrip(exchange='NFO', searchtext='NIFTY')`

**Comment by jayknayak** [comment]
api.searchscrip(exchange='NFO', searchtext='NIFTY') is not working.
I get: 
DEBUG:urllib3.connectionpool:https://api.shoonya.com:443 "POST /NorenWClientTP//SearchScrip HTTP/1.1" 404 58
DEBUG:NorenRestApiPy.NorenApi:{"stat":"Not_Ok","emsg":"No Data :  Exchange Not enabled"}

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Your F&O is not activated on your account; kindly raise the ticket from your Prism account for F&O activation.
