### ISSUE TITLE
Error 404: api.searchscrip not working

### ISSUE THREAD

**Issue by jayknayak** [Shoonya-Dev/ShoonyaApi-py#155]
`api.searchscrip(exchange='NFO', searchtext='NIFTY') ` is not working.
I get:

> DEBUG:urllib3.connectionpool:[https://api.shoonya.com:443](https://api.shoonya.com/) "POST /NorenWClientTP//SearchScrip HTTP/1.1" 404 58
> DEBUG:NorenRestApiPy.NorenApi:{"stat":"Not_Ok","emsg":"No Data : Exchange Not enabled"}

I tried changing the client apiKey and password as someone from their customer support team suggested. But still no luck. All the other APIs are working fine.

**Comment by TWP80** [comment]
Exchange Not enabled means you are not Enable Exchanges
go to https://prism.shoonya.com/services/index/requestServiceElement
and Enable Exchanges NFO(NSE FUTURE OPTION)

**Comment by jayknayak** [comment]
Issue automatically solved after an account reactivation service request fulfillment.
