### ISSUE TITLE
Getting websocket error issues very frequently. It starts with ERROR message and then a warning as given in description

### ISSUE THREAD

**Issue by Dukes14** [Shoonya-Dev/ShoonyaApi-py#159]
ERROR - invalid literal for int() with base 10: 'version="1.0"' - goodbye
WARNING - websocket run forever ended in exception, socket is already opened

  try:
        local_socket_opened = False
        while True:
            sleep(5)
            if socket_opened == True or local_socket_opened == True:
                continue

            ret = api.start_websocket(order_update_callback=event_handler_order_update,
                                      subscribe_callback=event_handler_quote_update,
                                      socket_open_callback=open_callback)

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please use the attached version and try again 

pip install websocket-client==v1.5.3
