### ISSUE TITLE
Option Chain - Not getting complete data

### ISSUE THREAD

**Issue by bhaskar-c** [Shoonya-Dev/ShoonyaApi-py#16]
Hi

I am trying to pull up the option chain for say Nifty with the following code

`chain = api.get_option_chain(exchange='NFO', tradingsymbol='NIFTY24FEB22F' , strikeprice=17200, count=5)`

Here is a sample response I get -

```
{"stat":"Ok",
"values": [ {"exch":"NFO","token":"52423","tsym":"NIFTY24FEB22C17200","optt":"CE","pp":"2","ls":"50","ti":"0.05","strprc":"17200.00"},
{"exch":"NFO","token":"52425","tsym":"NIFTY24FEB22C17250","optt":"CE","pp":"2","ls":"50","ti":"0.05","strprc":"17250.00"}
truncated .....
```
It does not return even basic things like:

- last traded price
- change in price
- open interest
- change in open interest
- volume
These are the least things that one expects to get from an option chain.

Instead it returns redundant things like lot size, exchange info, precision point etc.

Am I missing something obvious here ?

**Comment by Shoonya-Dev** [comment]
This is as expected. Please refer to example_market.py option o.

**Comment by 88pawankumarjha** [comment]
sample working syntax:

api.get_option_chain('NFO', 'NIFTY30NOV23F', '20000', 10)

replace symbol with cuurent month future
