### ISSUE TITLE
/EODChartData is giving blank [] now

### ISSUE THREAD

**Issue by satwikt** [Shoonya-Dev/ShoonyaApi-py#161]
Hi team,
we were using /EODChartData for more then 1 year it was working fine but now it has stopped working.
below is the api details i am using
https://api.shoonya.com/NorenWClientTP//EODChartData

request body: jData={"uid": "FA105208", "sym": "NSE:360ONE", "from": "1715149153.0", "to": "1715581153"}&jKey=key
response: []
response code: 200 ok

please let me know if you have changed something in api... or am i missing something

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please use correct trading symbol, like 360ONE-EQ
