### ISSUE TITLE
git code is not working in python 

### ISSUE THREAD

**Issue by siddeswervanga** [Shoonya-Dev/ShoonyaApi-py#163]
Git code is notworking python , getting below error can you please check it out 

![image](https://github.com/Shoonya-Dev/ShoonyaApi-py/assets/56863005/415178fa-cc64-4f05-a355-c2cb470e56c3)

DEBUG:NorenRestApiPy.NorenApi:Reply:{"request_time":"16:15:23 23-05-2024","stat":"Not_Ok","emsg":"Invalid Input : Invalid OTP"}

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please use the Google authentication code as a TOTP and run again; its working fine.
