### ISSUE TITLE
PyYAML=6.0.0 is not compatible with python 3.12 hence unable to complete install with pip and requirements.txt

### ISSUE THREAD

**Issue by vlog-mukhthar** [Shoonya-Dev/ShoonyaApi-py#167]
OS : ubuntu server lts 24.04
python version : 3.12.3
shoonya api version : 0.0.28

while running "pip install -r requirement.txt" there is error as "subprocess-exited-with-error" , this is because of PyYAML 6.0. 
Since the requirements.txt contains a "whl" it could not be modified without the source files. 

Looked for solution in issues and found a similar post : https://github.com/Shoonya-Dev/ShoonyaApi-py/issues/162
unable to find 0.0.22 version as mentioned. Request your support.

**Comment by suresh-n** [comment]
yes the new whl file cannot install.

**Comment by vlog-mukhthar** [comment]
> yes the new whl file cannot install.

changing the version of PyYAML version in the whl file will fix the problem which only you or your team can do? Or would you please recommend a working solution.

**Comment by sathishne** [comment]
Getting subprocess exited with error while running "pip install -r requirement.txt". did we get the issue resolved?

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please clone the documentation again and run this command; its working fine.
