### ISSUE TITLE
On place order api call, getting error  {'stat': 'Not_Ok', 'emsg': 'Invalid Input :  basic_string::at: __n (which is 0) >= this->size() (which is 0)'}

### ISSUE THREAD

**Issue by aykarageorge** [Shoonya-Dev/ShoonyaApi-py#168]
Error:

>  {'stat': 'Not_Ok', 'emsg': 'Invalid Input :  basic_string::at: __n (which is 0) >= this->size() (which is 0)'}

This API call was working fine till last Fri, and over the weekend now getting the above error.

Payload:

> {'ordersource': 'API', 'uid': '********', 'actid': '********', 'trantype': 'S', 'prd': 'C', 'exch': 'NSE', 'tsym': 'TATAPOWER-EQ', 'qty': '10', 'dscqty': '0', 'prctyp': 'MKT', 'prc': '', 'trgprc': '', 'ret': 'DAY', 'remarks': 'remarks', 'amo': 'No'}

**Comment by bhavesh116** [comment]
{
            'trantype': 'B',
            'prd': 'I',
            'ret': 'IOC',
            'exch': 'NSE',
            'tsym': `IDEA-EQ`,
            'qty': '1',
            'dscqty': '',
            'prctyp': 'MKT',
            'prc': '0'
        }

**Comment by bhushannsolanke** [comment]
were you able to solve the issue? facing similar issue since then it was working fine till last to last week

**Comment by aykarageorge** [comment]
> were you able to solve the issue? facing similar issue since then it was working fine till last to last week

Yes, I tried with 'prc': '0' instead of an empty string. It is resolved for now. It seems there were some updates made in the backend. Below the request that worked for me:

`{'ordersource': 'API', 'uid': '', 'actid': '', 'trantype': 'S', 'prd': 'C', 'exch': 'NSE', 'tsym': 'TATAPOWER-EQ', 'qty': '10', 'dscqty': '0', 'prctyp': 'MKT', 'prc': '0', 'trgprc': '', 'ret': 'DAY', 'remarks': 'remarks', 'amo': 'No'}`

**Comment by bhavesh116** [comment]
yes, it was resolved, the developer that guided me was really helpful and
professional

9993900116

**Comment by bhushannsolanke** [comment]
@aykarageorge Thanks! It worked :)
