### ISSUE TITLE
After last weekend, On place_order api call throws error code 400

### ISSUE THREAD

**Issue by webalgotrader** [Shoonya-Dev/ShoonyaApi-py#169]
On place_order api call throws error code 400, with response as invalid trans_type.

On further digging figured out that trans_type, which gets it value from buy_or_sell parameter, till last weekend used to work with "BUY" or "SELL".

Now, I feel the expected value is "B" or "S".

It is requested that the existing functionality may be kept on i.e. "BUY" or "SELL" also may be considered as a valid value for buy_or_sell parameter of api.place_order.

**Comment by bhushannsolanke** [comment]
were you able to solve it? facing same issue since then

**Comment by SHIVANIUM-GIT** [comment]
can you provide the code @webalgotrader @bhushannsolanke

**Comment by SHIVANIUM-GIT** [comment]
you have to do this 

```
ret = api.place_order(
            buy_or_sell="S",
            product_type="I",
            exchange="NFO",
            tradingsymbol=Strike,
            quantity=LOTSIZE,
            discloseqty=0,
            price_type="LMT",
            price=SL_point,
            trigger_price=SL_point,
            retention="DAY",
            remarks="order_sl",
        )  

```
