### ISSUE TITLE
Start time for get_time_price_series off by 23 mins - Closed without solving

### ISSUE THREAD

**Issue by gaurav-260** [Shoonya-Dev/ShoonyaApi-py#17]
https://github.com/Shoonya-Dev/ShoonyaApi-py/issues/10

Kindly solve this issue before closing it. We're spending time to make it better for everyone and just closing an issue without any explanation is extremely unprofessional of you.

**Comment by Shoonya-Dev** [comment]
reopened issue 10. Please provide additional info requested on the same.
