### ISSUE TITLE
required the previous version 22

### ISSUE THREAD

**Issue by arijitn1** [Shoonya-Dev/ShoonyaApi-py#173]
Dear @kambalatech @Shoonya-Dev @Nikhesh,

as the installation is getting failed for version 28, please share the last stable version, thanks,

**`**Error of version 28:**`**
_C:\Python_VsCode>pip install -r requirements.txt
Processing c:\python_vscode\dist\norenrestapi-0.0.28-py2.py3-none-any.whl (from -r requirements.txt (line 1))
Collecting PyYAML==6.0 (from NorenRestApi==0.0.28->-r requirements.txt (line 1))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]_

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

This issue is resolved Please clone the documentation again and run the command.

**Comment by ghost** [comment]
thanks @Shoonya-Dev
