### ISSUE TITLE
unable to run the program with different username and password 

### ISSUE THREAD

**Issue by pushkarajchillal** [Shoonya-Dev/ShoonyaApi-py#18]
File "C:\Users\lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\NorenRestApiPy\NorenApi.py", line 472, in place_order
    values["uid"]       = self.__username
AttributeError: 'ShoonyaApiPy' object has no attribute '_NorenApi__username'
[Finished in 1000ms]

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Can you Please Confirm the User Name ?

**Comment by pushkarajchillal** [comment]
now it working fine now no issue

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Confirmation.
