### ISSUE TITLE
Getting issue at websocket

### ISSUE THREAD

**Issue by mohit051091** [Shoonya-Dev/ShoonyaApi-py#191]
When running the below line,

api.start_websocket( order_update_callback=event_handler_order_update,
                     subscribe_callback=event_handler_feed_update, 
                     socket_open_callback=open_callback)

it is giving error

  File "D:\Python\Lib\site-packages\NorenRestApiPy\NorenApi.py", line 222, in start_websocket
    self.__websocket = websocket.WebSocketApp(url,
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

**Comment by sauravfinvasia-ai** [comment]
This error happens due to a wrong Python package being installed.
Step 1: Uninstall the wrong package
pip uninstall websocket
Step 2: Install the correct package
pip install websocket-client
