### ISSUE TITLE
Unable to trade in instruments with special characters in trading symbol

### ISSUE THREAD

**Issue by sakshamagarwal** [Shoonya-Dev/ShoonyaApi-py#21]
Hi,

The place order function throws a silent error when special characters are found in the trading symbol.

DEBUG:NorenRestApiPy.NorenApi:{"stat":"Not_Ok","emsg":"Invalid Input :  jData is not valid json object"}

res = api.place_order(
            buy_or_sell = 'B',
            product_type = 'C',
            exchange = 'NSE',
            tradingsymbol = "L&TFH-EQ",
            quantity = 1,
            discloseqty = 0,
            price_type = 'LMT',
            price = 60
        )

**Comment by adityakoli1508** [comment]
‘&’performs bitwise AND operation

**Comment by yubrajbhoi** [comment]
Hey, I am not able to reproduce this bug. I was able to place a buy limit order for "L&TFH-EQ" at 78 rupees. FYI, I am on Linux with the latest api version 0.0.18.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Use url encoding to avoid special char error for symbols like M&M.
