### ISSUE TITLE
Returning None in case of error

### ISSUE THREAD

**Issue by saiprasad-psp** [Shoonya-Dev/ShoonyaApi-py#22]
Returning the actual error instead of none would be really helpful in error handling.
Code from place_order function in NorenApi.py - 
if resDict['stat'] != 'Ok':            
            return None
Best Reagards,
Sai

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Please Try to pull Github again, If happening again kindly report it to apisupport@finvasia.in.
