### ISSUE TITLE
websocket market feed missing order quantities in market depth

### ISSUE THREAD

**Issue by shajeeck** [Shoonya-Dev/ShoonyaApi-py#25]
websocket market feed missing all order quantities in market depth `so1, bo1` etc

**Comment by yubrajbhoi** [comment]
I am also waiting for this feature. Other brokers already have it.

**Comment by TheCodeArtist** [comment]
>  order quantities in market depth so1, bo1

In the shoonya websocket feed, order quantities are available as `sq1`, `bq1` etc. right?

**Comment by alexfarseer** [comment]
Pass `NorenApi.FeedType.SNAPQUOTE` to `api.subscribe` like this: `api.subscribe(3456, feed_type=NorenApi.FeedType.SNAPQUOTE)`. You will get depth feed of 5 levels.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern

@shajeeck Hope Your Query has been Resolved.

**Comment by rushey17** [comment]
How to handle this error?
I am trying to connect web socket.


DEBUG:NorenRestApiPy.NorenApi:connecting to wss://shoonyatrade.finvasia.com/NorenWSTP/
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, run_forever() got an unexpected keyword argument 'ping_payload'

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.


**Solution :- by updating the python package pip update websocket_client**
