### ISSUE TITLE
Issue with Websocket on AWS.

### ISSUE THREAD

**Issue by vijay-arwapally** [Shoonya-Dev/ShoonyaApi-py#26]
Seems like websocket connection is not established on AWS EC2 instance.
Anyone else facing similar issue? any workaround?

**Comment by yubrajbhoi** [comment]
Can you connect to other WebSocket servers? AWS firewall rules are a mess.

**Comment by vijay-arwapally** [comment]
Yes previously I have kite connect of zerodha and it was working perfectly
fine

**Comment by vijay-arwapally** [comment]
Websocket for Shoonya API arent working with Windows EC2 instance, but do work with Linux EC2 instance.
I usually prefer Windows EC2 as it is simple, but downside is it is too slow.
But no clue why it doesnt work on windows 10 EC2 instance.
For now, since I am using Linux EC2 instance, can assume it is resolved.
