### ISSUE TITLE
Master Contracts for BSE and Indices

### ISSUE THREAD

**Issue by vijay-arwapally** [Shoonya-Dev/ShoonyaApi-py#27]
How to download master contract information for BSE and Indices?

**Comment by TheCodeArtist** [comment]
@Shoonya-Dev can you please update [tests/test_download_masters.py](https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/tests/test_download_masters.py) with URL/details of BSE token-symbols CSV?

Currently, it has only NSE, NFO, CDS, and MCX. No BSE! 😓

**Comment by vijay-arwapally** [comment]
> @Shoonya-Dev can you please update [tests/test_download_masters.py](https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/tests/test_download_masters.py) with URL/details of BSE token-symbols CSV?
> 
> Currently, it has only NSE, NFO, CDS, and MCX. No BSE! 😓

That I have already check bro. Need data for BSE

**Comment by vijay-arwapally** [comment]
@Shoonya-Dev Need your response ASAP.

**Comment by TheCodeArtist** [comment]
While we wait for @Shoonya-Dev to respond,
it appears that one can use the **`SC_CODE`** from the [BSE Bhavcopy](https://www.bseindia.com/markets/MarketInfo/BhavCopy.aspx),
as the **`token`** for scrips on the BSE exchange in ShoonyaAPI.

![image](https://user-images.githubusercontent.com/1897177/166189280-ad808b77-8d39-46e4-a3f8-d82301d7eec1.png)

For example, to subscribe for updates of **HDFC** scrip on the **BSE** exchange,
one can update [test_websocket_feed.py](https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/a3d3a41075f7b27e29e192bce1e3c32e51a05196/tests/test_websocket_feed.py#L53) as follows...
```
api.subscribe(['BSE|500010'])
```

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

We have Forwarded your request with Tech Team, Once we have received the Master Contracts for BSE and Indices, then will update you.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Please Check Below mention BSE Symbols Master File.
https://shoonya.finvasia.com/BSE_symbols.txt.zip
