### ISSUE TITLE
Please post a full sample program of any strategy like Super Trend

### ISSUE THREAD

**Issue by 284403** [Shoonya-Dev/ShoonyaApi-py#29]
Hello Sir, 

Please post a full sample program of trade using any indicator like super trend. In this program, please provide the structure like

1- login to finvasia
2- starting feed using web socket.
3- storing the feed data 
4- converting the tick data into 5 minutes OHLC candles
5- Applying super trend indicator on that 5 minutes candle data. 
6- Placing buy/sell orders based on ST indicator. 
7- Placing Target/SL order. Exiting based on ST reversals. 
8- Squaring off all positions based on exchange time. 
9- closing web socket and logging off. 

This would be super useful for people using the sample code and implement in real live trade after making their own modification. 

Best Regards.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

For More :- 
Please go through Shoonya API Documentation :- https://www.finvasia.com/api-documentation

API FAQ:- https://www.finvasia.com/faqs/apis
