### ISSUE TITLE
API Rate Limit

### ISSUE THREAD

**Issue by satvikjadhav** [Shoonya-Dev/ShoonyaApi-py#30]
Hi there. 

I would like to know what is the API rate limit for placing order? 
I am trying to execute an options strategy that will place more than 6 orders back to back. I would like to know what is the rate limit so I can add a delay in execution if needed.

Thank you.

**Comment by TheCodeArtist** [comment]
According to the API FAQs
> Currently, in our API, we provide 20 orders per second per service instance & 200 orders per minute per service instance.
> 
> Any third-party developers should not send more than 20 orders per second and 200 orders per minute to avoid any trading rejections.

Source: https://www.finvasia.com/faqs/apis/what-are-the-limits-for-placing-the-order-in-api

**Comment by Shoonya-Dev** [comment]
**Greetings from FINVASIA!**

Currently, in our API, we provide 20 orders per second per service instance & 200 orders per minute per service instance.

Any third-party developers should not send more than 20 orders per second and 200 orders per minute to avoid any trading rejections.

For More :- 
[](https://www.finvasia.com/faqs/apis/what-are-the-limits-for-placing-the-order-in-api)

**Comment by sbt987** [comment]
hi @Shoonya-Dev - is it still 20 orders per second per service instance & 200 orders per minute? The FAQ link is not working now.

I thought it is now 10 orders per second max after the new regulations a few months ago. 
I'm also interested to know the per minute, per hour, and per day limits.
