### ISSUE TITLE
Websocket Disconnection Handling

### ISSUE THREAD

**Issue by vijay-arwapally** [Shoonya-Dev/ShoonyaApi-py#31]
How to handle websocket disconnections? Anything to be done from user end or will the API try to reconnect until success?
Today I saw it lost connection and never could connect back. Continuous errors? Please let know what to do in this case?

**Comment by vijay-arwapally** [comment]
@Shoonya-Dev  Need your response ASAP.

**Comment by vijay-arwapally** [comment]
With version 0.0.19, close web socket API, this issue can be combated.

**Comment by janme2** [comment]
> 

I am also facing same issue. tick_data suddenly stops coming. Can you share how you resolved the issue?
