### ISSUE TITLE
Worst API Support.

### ISSUE THREAD

**Issue by vijay-arwapally** [Shoonya-Dev/ShoonyaApi-py#32]
- No guaranteed support.
- No community to track issues/discussion with similar users.
- Issues not being addressed from very long time.

**Is this the reason that the API is free? Maybe most of them would be ready to pay nominal charges for right support and right platform.
You would soon see ppl moving away incase the same keeps happening for prolonged time.** 

@Shoonya-Dev

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern

We have taking your suggestion , if you have concern you can directly report to [apisupport@finvasia.in](url)

Also we have currently using dev community group https://join.skype.com/uDwGsjP6ukMi,  on skype with concern team person in same group , you can direct put your issues there.
