### ISSUE TITLE
ModuleNotFoundError: No module named 'NorenRestApiPy'

### ISSUE THREAD

**Issue by himanshushekh** [Shoonya-Dev/ShoonyaApi-py#34]
I just started with this code, and after installing the requirements, I get this error. What might be wrong?
![image](https://user-images.githubusercontent.com/70792797/167245822-b2528117-5815-4f83-a544-fab883ba6eeb.png)

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Please Install libraries again.

**Comment by kalilinux-png** [comment]
> I just started with this code, and after installing the requirements, I get this error. What might be wrong? ![image](https://user-images.githubusercontent.com/70792797/167245822-b2528117-5815-4f83-a544-fab883ba6eeb.png)

pip install NorenRestApiPy
