### ISSUE TITLE
Order book api issues

### ISSUE THREAD

**Issue by rajindersingh041** [Shoonya-Dev/ShoonyaApi-py#37]
Hi,

I have written a code when I continuously check that status of orders from order book function myshoonya.get_order_book()
and it sometimes return null which stops and break my code. I have include try and except to handle this error but obviously if this function in future regularly return null then my algo will not work

![image](https://user-images.githubusercontent.com/10490016/167605221-c13eef37-1318-4e58-9fba-f9141c902e41.png)

Attach the error for your reference.

Happy to provide more details.

My function
![image](https://user-images.githubusercontent.com/10490016/167605426-4b667146-afb9-40bf-bccb-89aa9b3b8434.png)

**Comment by Shoonya-Dev** [comment]
Will need more details such as 
a. what frequency do you query for the orderbook
b. why not check order updates from websocket?

**Comment by selvaks030** [comment]
I am also facing the same issue some time api.get_order_book() returns none

I hit api.get_order_book() every one min completion like 9.:17:00 , 9:18:00

Also, can you pls let me know how to check order updates from websocket ?

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your mail.

Please provide the Answers to the queries as asked.

a. what frequency do you query for the orderbook
b. why not check order updates from websocket?

Team Shoonya
