### ISSUE TITLE
Unresolved issue(But closed) needs attention. #36

### ISSUE THREAD

**Issue by vijay-arwapally** [Shoonya-Dev/ShoonyaApi-py#39]
@Shoonya-Dev @kambalatech #36 (Look into #36 issue)

**Comment by PhillipCap** [comment]
added test_multiple_sessions example. Please refer to the same

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Yes Its Resolved & Fixed
