### ISSUE TITLE
API for OrderMargin is needed.

### ISSUE THREAD

**Issue by JagdishKolhe** [Shoonya-Dev/ShoonyaApi-py#40]
If we place basket order using API, we need to order margin, This API should be provided by Finvasia

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Query has been forwarded to Tech Team.

**Comment by chandangm** [comment]
+1. Getting error when you try to implement the same using the documentation. Please either provide or allow the api route like mentioned in the documentation.

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please check the documentation attached for more details. We already provide an order margin API.

https://shoonya.com/api-documentation#order-margin
