### ISSUE TITLE
Websocket issue 

### ISSUE THREAD

**Issue by ash21213** [Shoonya-Dev/ShoonyaApi-py#41]
DEBUG:NorenRestApiPy.NorenApi:connecting to wss://shoonyatrade.finvasia.com/NorenWSTP/
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [10], in <cell line: 18>()
     15     global feed_opened
     16     feed_opened = True
---> 18 api.start_websocket(order_update_callback=event_handler_order_update, subscribe_callback=event_handler_quote_update, socket_open_callback=open_callback)
     21 while(feed_opened==False):
     22     pass

File ~\AppData\Roaming\Python\Python39\site-packages\NorenRestApiPy\NorenApi.py:194, in NorenApi.start_websocket(self, subscribe_callback, order_update_callback, socket_open_callback, socket_close_callback, socket_error_callback)
    191 url = self.__service_config['websocket_endpoint'].format(access_token=self.__susertoken)
    192 reportmsg('connecting to {}'.format(url))
--> 194 self.__websocket = websocket.WebSocketApp(url,
    195                                         on_data=self.__on_data_callback,
    196                                         on_error=self.__on_error_callback,
    197                                         on_close=self.__on_close_callback,
    198                                         on_open=self.__on_open_callback)
    199 #th = threading.Thread(target=self.__send_heartbeat)
    200 #th.daemon = True
    201 #th.start()
    202 #if run_in_background is True:
    203 self.__ws_thread = threading.Thread(target=self.__ws_run_forever)

AttributeError: module 'websocket' has no attribute 'WebSocketApp'

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern

Following the Solution, Kindly Implement it at your end:- 
      
      1. ﻿correctly define the path to Shoonya file, ﻿I think it's a path error which is why the problem is with Noren.
      2. ﻿Just login and print the ret after login without any exceptional handle, ﻿If that will work then we can move forward, 
      because ﻿Sometimes if he changes the structure of folders this happens.
