### ISSUE TITLE
Invalid token entries in the master CSV lists

### ISSUE THREAD

**Issue by TheCodeArtist** [Shoonya-Dev/ShoonyaApi-py#43]
In the BSE and NSE master lists of tokens (download as shown in [test_download_masters.py](https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/tests/test_download_masters.py)),
there appear to be a few malformed entries.

Here are a few examples...

```
Exchange,Token,LotSize,Symbol,TradingSymbol,Instrument,TickSize, 
BSE,539115,1,ALAN,12:,SCOTT,0,
BSE,538789,1,BUDGE,12:,BUDGE,0,
BSE,536493,1,JK,12:,AGRI,0, 
```

Note how the `Instrument` field of these entries contains part of the complete symbol name?
Likely some issue while parsing the inputs to prepare these master CSV lists on the backend.

Please review and fix all such issues in the **logic used to prepare the 4 master lists**.

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your concern

Missing Entry added for BSE, Please Check Once & Confirm.
