### ISSUE TITLE
Product type is wrong in example and documentation

### ISSUE THREAD

**Issue by sultanarun** [Shoonya-Dev/ShoonyaApi-py#44]
C / M / H are given as product type in documentation. But for Intraday there exist I . This is nowhere mentioned

**Comment by sakthi379** [comment]
it comes with the login message. i too couldnt find it in documentation

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern

**For Your reference, the Following Product Types Can Use** 

1. "C" For CNC in NSE CASH & NFO 

2. "M" FOR NRML IN NSE CASH & NFO

3. "I" FOR MIS IN NSE CASH & NFO 

4. "B" FOR BRACKET ORDER IN NSE CASH  (BO)

5. "H" FOR COVER ORDER IN NSE CASH  (CO)
