### ISSUE TITLE
while login getting Invalid Vendor code err

### ISSUE THREAD

**Issue by helagoddr** [Shoonya-Dev/ShoonyaApi-py#47]
while login getting Invalid Vendor code err

{"stat":"Not_Ok","emsg":"Invalid Input :  Invalid Vendor code"}

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern

Kindly Regenerate Your API Key & Then Try.

**The following steps are needed to be followed for API key regeneration: -**
1. Log in to your PRISM portal. (https://prism.finvasia.com/)
2. Go to the profile on the top right. Click on “API Key”
3. regenerate an API key
4. Copy and paste the API key to your software.
