### ISSUE TITLE
get_option_chain(exchange, tradingsymbol, strikeprice, count)

### ISSUE THREAD

**Issue by bibinvargheset** [Shoonya-Dev/ShoonyaApi-py#48]
If get_option_chain(exchange, tradingsymbol, strikeprice, count): has the current price info about the options listed would be very helpful. It will avoid firing of several requests from each user as the next step of all this will be to get the price information these. 

Hence adding the price info in the same function or another based on this will reduce the server load  as well as the time for processing the requests for the user
 
A much better option chain format can be seen in https://marketsetup.in/documentation/jugaad-data/live/#live-index-option-chain.
also in Samco https://developers.stocknote.com/api/?python#option-chain

which gives more information about all the option chains based on that signal from nse.

Similarly the [get_security_info] can also be better with the current price

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

In our option chain, we already provided (exchange, trading symbol, strike price, count). Please refer to the below-attached documentation for more details:

https://shoonya.com/api-documentation#getmarketoptionchain
