### ISSUE TITLE
get_quotes

### ISSUE THREAD

**Issue by bibinvargheset** [Shoonya-Dev/ShoonyaApi-py#49]
**if get_quoes can take lists it would be faster  use**

simillar implematation in zerodha kite

_https://kite.trade/docs/pykiteconnect/v3/#kiteconnect.KiteConnect.quote
def quote(	self, *instruments)
Retrieve quote for list of instruments.

instruments is a list of instruments, Instrument are in the format of exchange:tradingsymbol. For example NSE:INFY_

**An ltp function would also be useful**

_https://kite.trade/docs/pykiteconnect/v3/#kiteconnect.KiteConnect.ltp
_def ltp(	self, *instruments)
Retrieve last price for list of instruments.

instruments is a list of instruments, Instrument are in the format of exchange:tradingsymbol. For example NSE:INFY_

**Comment by sabyasm** [comment]
@Shoonya-Dev Is there any ETA on this? Seems straightforward and would help developers a lot. Thank you!

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please use the below-attached format for the get_quotes:

```
exch  = 'NSE'
token = '26000'
ret = api.get_quotes(exchange=exch, token=token)
print(ret)
```
