### ISSUE TITLE
Basket Margin API

### ISSUE THREAD

**Issue by bibinvargheset** [Shoonya-Dev/ShoonyaApi-py#50]
https://finvasia.com/api-documentation#order-margin
https://finvasia.com/api-documentation#basket-margin  how to get basket margin

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Please refer below attached sample code for the order margin:

`jData={"uid":"FA30417","actid":"FA30417","exch":"NSE","tsym":"ACC-EQ","qty":"1","prc":"1600","s_prdt_ali":"I","token":"22","trantype":"B","prctyp":"LMT","ret":"DAY","remarks":"WC TEST Order","ordersource":"API", "prd":"M"}&jKey=541d3ad5c6f47138229d7734bb42ef3bdc662923f489fef08c9048b49367f4e5`
