### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by neothegod75** [Shoonya-Dev/ShoonyaApi-py#52]
` login  = api.login(userid=security.user, password="123", twoFA=security.factor2,
    vendor_code=security.vc, api_secret=security.app_key, imei=security.imei)`

This is returning none since 23-09-2022.

**Comment by alexfarseer** [comment]
First try to login with `logging.basicConfig(level=logging.DEBUG)`. That will show the error code. If your error code is `Invalid Vendor Code` you might be in luck. You just need to go to Prism and regenerate your API key. It should work after that (it worked for me).

**Comment by Shoonya-Dev** [comment]
factor2  is now TOTP as per exchange mandate. Kindly check with logging.basicConfig(level=logging.DEBUG).
