### ISSUE TITLE
get_daily_price_series() Response Issue 

### ISSUE THREAD

**Issue by raju-nichit** [Shoonya-Dev/ShoonyaApi-py#53]
Getting Response with some extra characters due to that pandas data frame not generating properly

![image](https://user-images.githubusercontent.com/31009314/192152788-a8ce0a76-0dbd-4ef1-9b58-99f52626da2e.png)

Code ->
  res = self.get_daily_price_series(exchange, token, startdate, enddate)
  daily_df = pd.DataFrame(res)

Dataframe output

![image](https://user-images.githubusercontent.com/31009314/192152846-550ef142-fb95-4a04-b6f8-51e7708e9890.png)

**Comment by trivalent** [comment]
+1
As visible, the response is not JSON compatible. @Shoonya-Dev request you to please adjust the response so it can be processed easily.

**Comment by trivalent** [comment]
Though this can be fixed at our end using the below syntax:
            def fix(data):
                import json
                return json.loads(data)

            response = self.api.finvasiaAPI.get_daily_price_series('NSE', instrument, startdate=start_time,
                                                                   enddate=end_time)
            response = [fix(x) for x in response]

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

The current outcome of your code can be modified as per your requirements.
