### ISSUE TITLE
Cancelling order prints unnecessary log

### ISSUE THREAD

**Issue by Guru24** [Shoonya-Dev/ShoonyaApi-py#54]
https://shoonyatrade.finvasia.com/NorenWClientTP//CancelOrder
{"request_time":"12:40:58 26-09-2022","stat":"Ok","result":"22092600265894"}

Above log gets printed when we cancel the  order even if I set the logging level to CRITICAL
Is there any log level which I can use to completely disabling the logs?

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

No, this log is for your reference, so there is no option to disable.
