### ISSUE TITLE
Websocket start but data is not received and also get_quote not work but search scripts work

### ISSUE THREAD

**Issue by rnhpl** [Shoonya-Dev/ShoonyaApi-py#55]
![image](https://user-images.githubusercontent.com/96116571/192223415-5234db2e-0341-4eea-9d7c-e97af4a54fb3.png)

**Comment by kambalatech** [comment]
refer example https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/tests/test_websocket_feed.py

**Comment by rnhpl** [comment]
ok
