### ISSUE TITLE
How to use end date to get only 1 day of data in 1 minute interval

### ISSUE THREAD

**Issue by justlearning-anything** [Shoonya-Dev/ShoonyaApi-py#56]
@Shoonya-Dev  Team, Your API's are great and I need your help in passing END DATE

Requirement : Pull only **28th September data for 1 minute interval** , I tried below but its still bringing 3 months data from API - Is it expected?   can this API give slicked 2 or 3 days data?

start_time = "28-09-2022 09:00:00"
end_time = "28-09-2022 09:30:00"
            
start_secs = time.strptime(start_time,'%d-%m-%Y %H:%M:%S')
start_secs=time.mktime(start_secs)

end_secs = time.strptime(end_time,'%d-%m-%Y %H:%M:%S')
end_secs=time.mktime(end_secs)

ret = api.get_time_price_series(exchange='NFO', token=sToken, starttime=start_time,**endtime=end_secs**, interval=1)

Kindly help me to pass the end time. Your help will be much appreciated.

**Comment by kambalatech** [comment]
please refer example
