### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by priyasdipu** [Shoonya-Dev/ShoonyaApi-py#57]
Hello,

Unable to login since 01-Oct morning. It was working fine till 30-Sep. I was passing my pancard in factor2 as paramenter

Today the error message is "emsg":"Invalid Input : Invalid OTP"}"

Where to generate the OTP & pass it here?

I tried to generate OTP while app login and passed the same as factor2. That worked only for once. If I run the script again, its showing same error message.

Anyone else facing same issue?

**Comment by TheCodeArtist** [comment]
> Unable to login since 01-Oct morning. It was working fine till 30-Sep. I was passing my pancard in factor2 as paramenter

Per recent regulations, this was the cut-off date to brokers to active OTP/TOTP for all such logins.

> I tried to generate OTP while app login and passed the same as factor2. That worked only for once

As the name suggests, OTP is a **O**ne **T**ime **P**assword.
You will have to re-generate a new OTP for each login, and provide it.

**Comment by priyasdipu** [comment]
Hi,

I understand that. But since I'm building & testing the code for a new strategy. I might have to tweak things multiple times and run. Do I have to provide OTP for each run?

Is there any workaround for this?

**Comment by yogesh0800** [comment]
Same issue i am also getting.

**Comment by yogesh0800** [comment]
Got the solution try below. use Your TTOP QR code here.

pip install pyotp
import pyotp

factor2 = pyotp.TOTP('T26#6#466#############').now()

**Comment by priyasdipu** [comment]
@yogesh0800 You saved my day. Thanks a lot.

**Comment by priyasdipu** [comment]
Hi,

I'm facing another type of issue now. I have used the sleep function for 60 secs if some of the conditions doesn't match.

It initiates fine but then it is unable to fetch the token (or any data) after the sleep.

Any help?

**Comment by DeepBhuptani** [comment]
create a login function and put it after your sleep function, it will login again after sleeping for 60sec 😄
