### ISSUE TITLE
end date not working in get_time_price_series()

### ISSUE THREAD

**Issue by debaonline4u** [Shoonya-Dev/ShoonyaApi-py#58]
Team @Shoonya-Dev, thanks for your hard work, in putting this API and everything in git. 
I have a query for get_time_price_series(). 
Here I am explaining my Requirements and related problems. 
**Requirements**: I want to fetch data as per my desired start and end date. 
Here is my start date: 2020-10-05 00:00:00 and its timestamp: 1601836200
Here is my end date: 2021-10-05 00:00:00 and its timestamp: 1633372200

I am here fetching 5-minute interval data for 1 year. 
Here is my code snippet: 

`end_date = datetime.today() - timedelta(365)`
`end_date = end_date.replace(hour = 0, minute = 0, second = 0, microsecond = 0)`
`start_date = end_date - timedelta(days = 1*365)`

Fetching data (Here I have given only starttime, endtime is not provided here)
`new_data = api.get_time_price_series(exchange='NSE', token='2885', starttime=start_date.timestamp(), 
                                     interval=5)`
Data successfully retrieved
`df_new = pd.DataFrame(new_data)`

**Here I have received data from 05-10-2021 to 04-10-2022, but I was actually expecting data from 05-10-2020 to 04-10-2022.** 

In the same function "get_time_price_series()" - If I am passing endtime argument, then I am actually getting warning and no data are received. 
Error message: `DEBUG:NorenRestApiPy.NorenApi:{"stat":"Not_Ok","request_time":"16:20:39 05-10-2022","emsg":"Error Occurred : 5 \"no data\""}`

Team @Shoonya-Dev , kindly lookinto this, and Please reply. 

**Second Question**
Is there any restriction to fetch time series data or historical data. 
Like in Kite (from Zerodha), they have restrictions for each intervals - below I have mentioned

-  minute - 60 days
-  3 minute - 100 days
-  5 minute - 100 days
-  10 minute - 100 days
-  15 minute - 200 days
-  30 minute - 200 days
-  60 minute - 400 days
-  day - 1000 days

Hope, I have explained the problem clearly. 
Your guidance on this matter is highly appreciated. 
Thank you.

**Comment by Shoonya-Dev** [comment]
fixed

**Comment by debaonline4u** [comment]
Dear Team, is this issue really resolved?
