### ISSUE TITLE
Unable to istall the libraries with whl file.

### ISSUE THREAD

**Issue by qFactorin** [Shoonya-Dev/ShoonyaApi-py#6]
Tried pip install using the requirements.txt file. NorenRestApiPy library does get installed but unable to get api_helper installed on my machine. Am I missing something here? Any help in this regard would be really helpful.

**Comment by gmnabeel** [comment]
i did pip install -r requirements.txt ! works fine

**Comment by gmnabeel** [comment]
if you know what to enter in secret key, imei and vc field let me know

**Comment by Shoonya-Dev** [comment]
pip install -r requirements.txt
or pip install ShoonyaAPI.whl
