### ISSUE TITLE
how to pull historical data 

### ISSUE THREAD

**Issue by ghostjat** [Shoonya-Dev/ShoonyaApi-py#63]
Hi,
i am trying to pull historical data using 
`get_daily_price_series`
`ret = api.get_daily_price_series(exchange='NSE', tradingsymbol='RELIANCE-EQ', startdate=start.timestamp(), enddate=end.timestamp())
`
i am getting nothing, completely empty response from server.
need help

**Comment by DeepBhuptani** [comment]
_hope this helps ↓_

import datetime

def unixtime(timee):
    return datetime.datetime.timestamp(datetime.datetime.strptime(timee, "%d%m%Y,%H:%M:%S"))

st = unixtime('14102022,09:15:00')
et = unixtime('28102022,15:30:00')
re = api.get_daily_price_series(exchange='NSE', tradingsymbol='RELIANCE-EQ', startdate=st, enddate=et)
print(re)

output:
['{"time":"28-OCT-2022", "into":"2465.00", "inth":"2535.00", "intl":"2459.45", "intc":"2526.15", "ssboe":"1666915200", "intv":"8126824.00"}',
'{"time":"27-OCT-2022", "into":"2458.00", "inth":"2468.45", "intl":"2432.80", "intc":"2451.15", "ssboe":"1666828800", "intv":"5774775.00"}',
'{"time":"25-OCT-2022", "into":"2499.00", "inth":"2499.00", "intl":"2438.00", "intc":"2441.55", "ssboe":"1666656000", "intv":"5645639.00"}',
'{"time":"24-OCT-2022", "into":"2460.00", "inth":"2502.50", "intl":"2455.30", "intc":"2479.85", "ssboe":"1666569600", "intv":"1555270.00"}',
'{"time":"21-OCT-2022", "into":"2507.70", "inth":"2516.80", "intl":"2467.00", "intc":"2471.60", "ssboe":"1666310400", "intv":"3804352.00"}']

**Comment by ghostjat** [comment]
Client error: `POST https://api.shoonya.com/NorenWClientTP/EODChartData` 
Resulted in a `405 Method Not Allowed`
Response: `Method Not Allowed`
