### ISSUE TITLE
websocket not working

### ISSUE THREAD

**Issue by siddup30** [Shoonya-Dev/ShoonyaApi-py#79]
Hi im trying to use websocket but feed opener is always false, callback is not getting triggered even after succesfull login 

**please help.**

import pyotp
from api_helper import ShoonyaApiPy
import config
from time import sleep
import pandas as pd
from datetime import datetime,date

#Login
api = ShoonyaApiPy()
ret = api.login(userid=config.user, password=config.pwd, twoFA=pyotp.TOTP(config.otpToken).now(), vendor_code=config.vc, api_secret=config.app_key, imei=config.imei)
print(ret)

feed_opened = False

def event_handler_feed_update(tick_data):
    print(f"feed update {tick_data}")

def open_callback():
    global feed_opened
    feed_opened = True
    
def event_handler_order_update(order):
    print(f"order feed {order}")

api.start_websocket( order_update_callback=event_handler_order_update,
                     subscribe_callback=event_handler_feed_update, 
                     socket_open_callback=open_callback)

while(feed_opened==False):
    pass

api.subscribe('NSE|13')

#subscribe to multiple tokens
api.subscribe(['NSE|22', 'BSE|522032'])

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Please Check Your Code, Websocket is working perfactly.
