### ISSUE TITLE
Certificate error.

### ISSUE THREAD

**Issue by avinashily** [Shoonya-Dev/ShoonyaApi-py#82]
*** requests.exceptions.SSLError: HTTPSConnectionPool(host='shoonyatrade.finvasia.com', port=443): Max retries exceeded with url: /NorenWClientTP//QuickAuth (Caused by SSLError(SSLCertVerificationError("hostname 'shoonyatrade.finvasia.com' doesn't match 'shoonya.finvasia.com'")))

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

It's still reading the old URL (shoonyatrade.finvasia.com) which the client will have to verify cross by himself.
Please update/ Pull **api_helper.py** from Github (https://github.com/Shoonya-Dev/ShoonyaApi-py)
There are some changes in the Endpoint URL.

**NEW LIVE ENDPOINT URL:-**        
host='https://api.shoonya.com/NorenWClientTP/'
websocket='wss://api.shoonya.com/NorenWSTP/'
