### ISSUE TITLE
Websocket Error - Not Working

### ISSUE THREAD

**Issue by hardikchhajar** [Shoonya-Dev/ShoonyaApi-py#83]
WARNING:NorenRestApiPy.NorenApi:websocket run forever ended in exception, WebSocketApp.run_forever() got an unexpected keyword argument 'ping_payload'

its showing this: |

NorenApi File:-
def __ws_run_forever(self):
        
        while self.__stop_event.is_set() == False:
            try:
                self.__websocket.run_forever( ping_interval=3,  ping_payload='{"t":"h"}')
            except Exception as e:
                logger.warning(f"websocket run forever ended in exception, {e}")
login file:-
class ShoonyaApiPy(NorenApi):
    def __init__(self):
        NorenApi.__init__(self, host='https://api.shoonya.com/NorenWClientTP/', websocket='wss://api.shoonya.com/NorenWSTP/')

logging.basicConfig(level=logging.DEBUG)
api = ShoonyaApiPy()

main file:-
from login import *
import pandas as pd
import logging
logging.basicConfig(level = logging.DEBUG)
def event_handler_order_update(message):
    print("order event: " + str(message))

SYMBOLDICT = {}
def event_handler_feed_update(message):
    global SYMBOLDICT
    key = message['e'] + '|' + message['tk']

    if key in SYMBOLDICT:
        symbol_iNFO =  SYMBOLDICT[key]
        symbol_iNFO.update(message)
        SYMBOLDICT[key] = symbol_iNFO
    else:
        SYMBOLDICT[key] = message

    print(SYMBOLDICT[key])
    # print(SYMBOLDICT[key]['lc'],"",SYMBOLDICT[key]['uc'],"",SYMBOLDICT[key]['bq1'],"",SYMBOLDICT[key]['bp1'],"",SYMBOLDICT[key]['sp1'],"",SYMBOLDICT[key]['sq1'])
    df = pd.DataFrame.from_dict(SYMBOLDICT).transpose()
    df.reset_index(drop=True,inplace=True)
    print(df)
    
    for i in range(len(df)):
        exch = df['e'].iloc[i]
        ls = df['ls'].iloc[i]
        ts = df['ts'].iloc[i]
        uc = df['uc'].iloc[i]
        lc = df['lc'].iloc[i]
        api.place_order("S","M",exch,ts,ls,0,"LMT",uc,retention="DAY")        

def open_callback():
    global feed_opened
    feed_opened = True

ret = api.start_websocket(order_update_callback=event_handler_order_update, subscribe_callback=event_handler_feed_update, socket_open_callback=open_callback)

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

by updating the **python package pip update websocket_client**
