### ISSUE TITLE
websocket feed not working 

### ISSUE THREAD

**Issue by SSV0726** [Shoonya-Dev/ShoonyaApi-py#84]
I am receiving order updates , but market data updates  

> i.e  subscribe_callback=event_handler_quote_update 

is not working , and not receiving any connection there . 

ERROR:websocket:error from callback <bound method NorenApi.__on_data_callback of <api_helper.ShoonyaApiPy object at 0x7fdd3574e190>>: name 'api' is not defined

In all 3 versions of NorenRestApiPy ( v0.0.19 , v0.0.20 , v0.0.22 )

**Comment by PhillipCapital-India** [comment]
Either in your event_handler_quote_update you are using api which is not declared 
or
you are incorrectly trying to use api declared in api_helper.py

**Comment by Shoonya-Dev** [comment]
Please check  event_handler_quote_update if you are using api object without declaring. or if you are using from api from apihelper import the same.
