### ISSUE TITLE
User Blocked due to multiple wrong attempts

### ISSUE THREAD

**Issue by rushey17** [Shoonya-Dev/ShoonyaApi-py#87]
Hi Team,

I am getting the following error message while I tried to login, can you please help this issue to be resolved.Thanks.

**DEBUG:NorenRestApiPy.NorenApi:Reply:{"request_time":"01:24:04 10-01-2023","stat":"Not_Ok","emsg":"Invalid Input : User Blocked due to multiple wrong attempts"}**

**Comment by suresh-n** [comment]
I think you can contact the shoonya support from prism chat that is the fastest way.
