### ISSUE TITLE
Not able to get price series

### ISSUE THREAD

**Issue by Tarun0000** [Shoonya-Dev/ShoonyaApi-py#88]
ret = api.get_time_price_series(exchange='NSE', token=eq_name[eq], starttime=lastBusDay.timestamp(),interval=5)
  File "C:\ProgramData\Anaconda3\envs\algotrading\lib\site-packages\NorenRestApiPy\NorenApi.py", line 872, in get_time_price_series
    values["uid"]       = self.__username
AttributeError: 'ShoonyaApiPy' object has no attribute '_NorenApi__username'

**Comment by Shoonya-Dev** [comment]
seems like you are not logged in.

**Comment by Tarun0000** [comment]
I'm login sucessfully

**Comment by Tarun0000** [comment]
NorenRestApiPy.NorenApi:Reply:{"request_time":"10:45:42 11-01-2023","stat":"Not_Ok","emsg":"Invalid Input : Invalid OTP"}
