### ISSUE TITLE
Targeting Endpoint for EOD is not working

### ISSUE THREAD

**Issue by ghostjat** [Shoonya-Dev/ShoonyaApi-py#89]
Targeting Endpoint: `POST https://api.shoonya.com/NorenWClientTP/EODChartData` 
Resulted in a `405 Method Not Allowed`
Response: `Method Not Allowed`

_Originally posted by @ghostjat in https://github.com/Shoonya-Dev/ShoonyaApi-py/issues/63#issuecomment-1374894792_

**Comment by Shoonya-Dev** [comment]
method is now enabled on the server. Please recheck
