### ISSUE TITLE
Start time of time series incorrect

### ISSUE THREAD

**Issue by gaurav-260** [Shoonya-Dev/ShoonyaApi-py#9]
On initiating a timeseries with hh=0, mm=0, ss=0 for any date, the start of the data pull happens from 10:30 AM. In order to pull data from 9:15 to 10:30, one has to go 1 day back and pull that data. Can you look into the time series function built.

**Comment by Shoonya-Dev** [comment]
please check your Timezone. Also can you paste the value of the start time passed to the method?

**Comment by gaurav-260** [comment]
This is fixed, I am in the US, so the datetime was taking 12AM EST, which was 10:30 AM IST, hence the above issue. Specifying the timezone fixed it. THnak you!
