### ISSUE TITLE
Not able to download dist file

### ISSUE THREAD

**Issue by pal5221** [Shoonya-Dev/ShoonyaApi-py#95]

**Comment by Shoonya-Dev** [comment]
@pal5221 
Greetings from Shoonya!

Thanks for your concern.

I have shared the [URL](https://github.com/Shoonya-Dev/ShoonyaApi-py/blob/master/dist/NorenRestApiPy-0.0.22-py2.py3-none-any.whl) to download the dist file. Please try to download again.

Team Shoonya
