### ISSUE TITLE
10 seconds delay in api.get_time_price_series

### ISSUE THREAD

**Issue by selvaks030** [Shoonya-Dev/ShoonyaApi-py#96]
Hi,

api.get_time_price_series(exchange='NFO', token=cetoken, starttime=lastBusDay.timestamp(), interval=5)

**get_time_price_series** give results only after 10 seconds ,,  if we check 10.55 am candle data at 11:00:00 am getting none response

i tried checking from 11:00:01 to 11:00:08 still none results coming.. only at 11:00:10 i get data

10 second delay causes huge slippage ,, can u pls check this issue

**Comment by aliveoceans** [comment]
> Hi,
> 
> api.get_time_price_series(exchange='NFO', token=cetoken, starttime=lastBusDay.timestamp(), interval=5)
> 
> **get_time_price_series** give results only after 10 seconds ,, if we check 10.55 am candle data at 11:00:00 am getting none response
> 
> i tried checking from 11:00:01 to 11:00:08 still none results coming.. only at 11:00:10 i get data
> 
> 10 second delay causes huge slippage ,, can u pls check this issue

This is a serious issue. It needs to be fixed ASAP.

**Comment by selvaks030** [comment]
Sorry my bad

lastBusDay.replace(hour=9, minute=16, second=0, microsecond=0,day=today,month=currmonth)

I missed to use day & month parameter to fetch result

After using month & day parameter am getting result in 1 sec

we can close this ticket
