### ISSUE TITLE
get_daily_price_series not having indices

### ISSUE THREAD

**Issue by pannet1** [Shoonya-Dev/ShoonyaApi-py#99]
https://github.com/Shoonya-Dev/ShoonyaApi-py/issues/63#issuecomment-1296231695

works well. however if i try to get NIFTY BANK, i get no response

```
import datetime

def unixtime(timee):
    return datetime.datetime.timestamp(datetime.datetime.strptime(timee, "%d%m%Y,%H:%M:%S"))

st = unixtime('10102022,09:15:00')
et = unixtime('28102022,15:30:00')
re = api.get_daily_price_series(exchange='NSE', tradingsymbol='NIFTY BANK', startdate=st, enddate=et)
print(re)

**Comment by Govardhanab3339** [comment]
Hi , I am also not getting the responses from  the get_daily_price_series for exchange NSE and tradingsymbol as indices "NIFTY INDEX and NIFTY BANK" @Shoonya-Dev : kindly help @trivalent @pannet1 @kambalatech @Nikhesh
